# Adapted from https://gist.github.com/jhass/a5ae80d87f18e53e7b56

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/PreferredHashMethods:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: "inject"

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Style/RaiseArgs:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Lint/SuppressedException:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Lint/Debugger:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false